export const FETCH_ALL_JOBS_START = "FETCH_ALL_JOBS_START";
export const FETCH_ALL_JOBS_SUCCESS = "FETCH_ALL_JOBS_SUCCESS";
export const FETCH_ALL_JOBS_FAIL = "FETCH_ALL_JOBS_FAIL";
export const FETCH_SINGLE_JOB_SUCCESS = "FETCH_SINGLE_JOB_SUCCESS";
